#ifndef SENSORINDEXES_H
#define SENSORINDEXES_H

enum Indexes
{
    CPU_LOAD_TOTAL = 0x002F,
    CPU_LOAD_CORE_MAX = 0X0030,
    CPU_PACKAGE = 0X0031,
    CPU_TEMPERATURE_CORE = 0X004A,
    RAM_USED = 0X004F,
    RAM_AVAILABLE = 0X0050,
    RAM_LOAD_MEMORY = 0X0051,
    RAM_VIRTUAL_USED = 0X0052,
    RAM_VIRTUAL_AVAILABLE = 0X0053,
    RAM_LOAD_VIRTUAL_MEMORY = 0X0054,
    GPU_FRAMERATE = 0X0057,
    GPU_PACKAGE = 0X0070,
    GPU_TEMPERATURE_CORE = 0X0073,
    GPU_TEMPERATURE_HOT_SPOT = 0X0074,
    GPU_LOAD_CORE = 0X0078,
    GPU_LOAD_MEMORY = 0X0079
};

static const Indexes ALL_INDEXES[] = {
    CPU_LOAD_TOTAL,
    CPU_LOAD_CORE_MAX,
    CPU_PACKAGE,
    CPU_TEMPERATURE_CORE,
    RAM_USED,
    RAM_AVAILABLE,
    RAM_LOAD_MEMORY,
    RAM_VIRTUAL_USED,
    RAM_VIRTUAL_AVAILABLE,
    RAM_LOAD_VIRTUAL_MEMORY,
    GPU_FRAMERATE,
    GPU_PACKAGE,
    GPU_TEMPERATURE_CORE,
    GPU_TEMPERATURE_HOT_SPOT,
    GPU_LOAD_CORE,
    GPU_LOAD_MEMORY};
#endif